# Generated by Django 4.1.3 on 2022-12-14 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_description_post_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='content',
        ),
    ]
